quarkus.http.port=8088
kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.order-events-in.connector=smallrye-kafka
mp.messaging.incoming.order-events-in.topic=order-events
mp.messaging.incoming.order-events-in.group.id=inventory-service
mp.messaging.incoming.order-events-in.value.deserializer=com.mohammed.inventory.messaging.OrderCreatedEventDeserializer