quarkus.http.port=8088
kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.order-events-in.connector=smallrye-kafka
mp.messaging.incoming.order-events-in.topic=order-events
mp.messaging.incoming.order-events-in.group.id=inventory-service
mp.messaging.incoming.order-events-in.value.deserializer=com.mohammed.inventory.messaging.OrderCreatedEventDeserializer
mp.messaging.incoming.order-events-in.value.serializer=com.mohammed.inventory.messaging.OrderCreatedEventSerializer
mp.messaging.incoming.order-events-in.failure-strategy=delayed-retry-topic
mp.messaging.incoming.order-events-in.retry-attempts=3
mp.messaging.incoming.order-events-in.dead-letter-queue.topic=order-events-dlq