quarkus.http.port=8088

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/inventory_db

quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.migrate-at-start=true



kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.order-events-in.connector=smallrye-kafka
mp.messaging.incoming.order-events-in.topic=order-events
mp.messaging.incoming.order-events-in.group.id=inventory-service
mp.messaging.incoming.order-events-in.value.deserializer=com.mohammed.inventory.messaging.OrderCreatedEventDeserializer
mp.messaging.incoming.order-events-in.value.serializer=com.mohammed.inventory.messaging.OrderCreatedEventSerializer
mp.messaging.incoming.order-events-in.failure-strategy=delayed-retry-topic
mp.messaging.incoming.order-events-in.retry-attempts=3
mp.messaging.incoming.order-events-in.dead-letter-queue.topic=order-events-dlq



mp.messaging.outgoing.inventory-events-out.connector=smallrye-kafka
mp.messaging.outgoing.inventory-events-out.topic=inventory-events
mp.messaging.outgoing.inventory-events-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.inventory-events-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer